app/urls.py
from app import views
from django.urls import path

app_name = 'app'
urlpatterns = [
    path('', views.CarList.as_view(), name='car-list'),
    path('create/', views.CarCreate.as_view(), name="car-create"),
    path("update<int:pk>/", views.CarUpdate.as_view(), name="car-update"),
    path("delete<int:pk>/", views.CarDelete.as_view(), name="car-delete"),
]

car_catalog/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace="app")),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

app/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Car(models.Model):

    MECHANIC = 1
    AUTOMATIC = 2
    ROBOTIC = 3

    GEARBOX_CHOICES = [
        (MECHANIC, "механика"),
        (AUTOMATIC, "автомат"),
        (ROBOTIC, "робот"),
    ]

    manufacturer = models.CharField(
        verbose_name = u"Производитель",
        max_length=30
        )
    model = models.CharField(
        verbose_name = u"Модель",
        max_length=30
        )
    release_year = models.IntegerField(
        verbose_name = u"Год выпуска",
        validators=[
            MinValueValidator(1900),
            MaxValueValidator(2020)
            ]
        )
    gearbox = models.SmallIntegerField(
        verbose_name = u"Коробка передач",
        choices=GEARBOX_CHOICES,
        default=0
        )
    color = models.CharField(
        verbose_name = u"Цвет",
        max_length=30,
        )
    photo = models.ImageField(
        verbose_name='Фото',
        upload_to='photos',
        blank=True
        )

    class Meta:
        verbose_name = u"Автомобиль"
        verbose_name_plural = u"Автомобили"

    def __str__(self):
        return f'{self.manufacturer} {self.model}'


app/forms.py
from django import forms  
from app.models import Car
from django.forms.widgets import ClearableFileInput

class MyClearableFileInput(ClearableFileInput):
    initial_text = 'Текущяя'
    input_text = 'Изменить'
    clear_checkbox_label = 'Удалить'

class CarForm(forms.ModelForm):
    manufacturer = forms.CharField(
        label='Производитель',
        widget=forms.TextInput(
            attrs={
                'required': True,
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите производителя автомобиля'
            }
        )
    )
    model = forms.CharField(
        label='Модель',
        widget=forms.TextInput(
            attrs={
                'required': True,
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите модель автомобиля'
            }
        )
    )
    release_year = forms.CharField(
        label='Год выпуска',
        widget=forms.TextInput(
            attrs={
                'required': True,
                'type': 'number',
                'class': 'form-control',
                'placeholder': 'Введите год выпуска автомобиля'
            }
        )
    )
    gearbox = forms.TypedChoiceField(
        choices=Car.GEARBOX_CHOICES,
        label='Коробка передач',
        widget=forms.Select(
            attrs={
                'required': True,
                'class': 'form-control'
            }
        )
    )
    color = forms.CharField(
        label='Цвет',
        widget=forms.TextInput(
            attrs={
                'required': True,
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите цвет автомобиля'
            }
        )
    )
    photo = forms.ImageField(
        label= 'Фото',
        required=False,
        widget= MyClearableFileInput(
            attrs={
                'class': 'form-control',
                'accept': '.jpg,.jpeg,.png,.gif'
            }
        )
    )
    class Meta:
        model = Car
        fields = '__all__'

app/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.template import loader
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from app.models import Car
from app.forms import CarForm

class CarDelete(LoginRequiredMixin, DeleteView):
    login_url = '/'
    redirect_field_name = ''
    model = Car
    success_url = reverse_lazy('app:car-list')
    template_name = 'car_delete.html'

class CarUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/'
    redirect_field_name = ''
    model = Car
    form_class = CarForm
    success_url = reverse_lazy('app:car-list')
    template_name = 'car_edit.html'

class CarCreate(LoginRequiredMixin, CreateView):
    login_url = '/'
    redirect_field_name = ''
    model = Car
    form_class = CarForm
    success_url = reverse_lazy('app:car-list')
    template_name = 'car_edit.html'

class CarList(ListView):
    model = Car
    template_name = 'car_list.html'

    def get_queryset(self):
        if 'btnSearch' in self.request.GET:
            query = self.request.GET.get('search', '')
            flag = False
            if query == 'механика' or query == 'Mеханика' \
                or query == 'МЕХАНИКА':
                query = 1
                flag = True
            elif query == 'автомат' or query == 'Автомат' \
                or query == 'АВТОМАТ':
                query = 2
                flag = True
            elif query == 'робот' or query == 'Робот' \
                or query == 'РОБОТ':
                query = 3
                flag = True
            if flag:
                car_list = Car.objects.filter(
                    gearbox=query)
            else:
                car_list = Car.objects.filter(
                    Q(manufacturer__icontains=query)|
                    Q(model__icontains=query)|
                    Q(release_year__icontains=query)|
                    Q(color__icontains=query))
            return car_list
        return Car.objects.all()

    def dispatch(self, request, *args, **kwargs):
        if 'btnLogIn' in request.POST:
            template = loader.get_template('car_list.html')
            cars = Car.objects.all()
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                login(request, form.get_user())
                msg_data = {"errmsg": 0,
                            "object_list": cars,}
            else:
                msg_data = {"errmsg": 1,
                            "object_list": cars,}
            return HttpResponse(template.render(msg_data, request)) 
            # return redirect('/')
        elif 'btnLogOut' in request.POST:
            logout(self.request)
            return redirect('/')
        elif 'btnAddAuto' in request.POST:
            return redirect('/create/')
        return super(CarList, self).dispatch(request, *args, **kwargs)


templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" sizes="16x16" href="media/icon/logo.png">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    {% block content %}{% endblock %}
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/car_delete.html
{% extends 'base.html' %}

{% block title %}Удаление авто из списка{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <form enctype="multipart/form-data" class="mt-5 text-center" method="POST"> 
                    {% csrf_token %}
                    <h3>Вы действительно хотите удалить автомобиль "{{ object }}"?</h3>
                    <input class="btn btn-success my-3" type="submit" value="Удалить">
                    <a class="btn btn-danger my-3" href="{%url 'app:car-list'%}">Отмена</a>
                </form>
            </div>
        </div>  
    </div>

{% endblock %}

templates/car_edit.html
{% extends 'base.html' %}

{% block title %}Форма создания и редактирования{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <form enctype="multipart/form-data" class="mx-auto mt-3 w-50" method="post"> 
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-success my-3" type="submit" value="Сохранить">
                    <a class="btn btn-danger my-3" href="{%url 'app:car-list'%}">Отмена</a>
                </form>
            </div>
        </div>  
    </div>

{% endblock %}

templates/car_list.html
{% extends 'base.html' %}

{% block title %}Список автомобилей{% endblock %}

{% block content %}
    <header class="container-fluid sticky-top bg-secondary" style="border:1px solid #fff;">
        <div class="d-flex flex-md-row flex-sm-column flex-column justify-content-between align-items-center">
            <div class="text-white my-2">
                <img src="media/icon/logo.png" alt="">
                {% if user.is_authenticated %}
                Привет, {{ user.username }}!
                {% else %}
                Привет, гость!
                {% endif %}
            </div>
            <form class="form-group d-flex my-2" method="GET" action="{% url 'app:car-list' %}">
                <input class="form-control" style="min-width:150px;max-width:300px;" type="text" placeholder="Поиск" aria-label="Search" name="search">
                <button class="btn btn-warning mx-2" type="submit" name="btnSearch">Поиск</button>
            </form>
            <form class="form-group d-flex my-2" method="POST">
            {% csrf_token %}
            {% if user.is_authenticated %}
                <button class="btn btn-warning mr-2" type="submit" name="btnAddAuto">Добавить авто</button>
                <button class="btn btn-warning" type="submit" name="btnLogOut">Выйти</button>
            {% else %}
                <input type="text" class="form-control text-center mr-2" style="min-width:120px;max-width:160px;" name="username" autofocus="" required="" id="id_username" placeholder="Логин">
                <input type="password" class="form-control text-center mr-2" style="min-width:120px;max-width:160px;" name="password" required="" id="id_password" placeholder="Пароль">
                <button class="btn btn-warning" type="submit" name="btnLogIn">Войти</button>
            {% endif %}
            </form>
        </div>
    </header>
    {%if errmsg == 1 %}
    <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
        <strong>Неверный логин или пароль. Попробуйте ввести ещё раз!</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 my-3">
                <div class="row">
                    {% for car in object_list %}
                    <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
                        <div class="card shadow p-1 bg-secondary rounded">
                            <div style="position:relative;padding-bottom:75%;">
                            {%if car.photo %}
                                <img src="{{ car.photo.url }}" class="w-100 h-100" style="position:absolute;top:0;left:0;object-fit:cover;" alt="">
                            {% else %}
                                <img src="media/photos/default.jpg" class="w-100 h-100" style="position:absolute;top:0;left:0;object-fit:cover;" alt="">
                            {% endif %}
                            </div>
                            <div class="card-body text-white">
                                <h4 class="card-title font-weight-bold">{{ car.manufacturer }}</h4>
                                <p class="card-title"><span class="font-weight-bold text-dark">Модель:</span> {{ car.model }}</p>
                                <p class="card-title"><span class="font-weight-bold text-dark">Год выпуска:</span> {{ car.release_year }}</p>
                                <p class="card-title"><span class="font-weight-bold text-dark">Коробка передач: </span>
                                {%if car.gearbox == 1 %}
                                    механика
                                {% elif car.gearbox == 2 %}
                                    автомат
                                {% elif car.gearbox == 3 %}
                                    робот
                                {% endif %}
                                </p>
                                <p class="card-title"><span class="font-weight-bold text-dark">Цвет:</span> {{ car.color }}</p>
                                {% if user.is_authenticated and user.is_superuser %}
                                <div class="d-flex flex-row justify-content-between">
                                    <a href="{%url 'app:car-update' car.id %}" class="btn btn-warning">Изменить</a>
                                    <a href="{% url 'app:car-delete' car.id %}" class="btn btn-danger">Удалить</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                  {% endfor %}
                </div>
            </div>  
        </div>  
    </div>

{% endblock %}